import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { ChevronRight } from "lucide-react";

const AdSensePolicy = () => {
  return (
    <>
      <Helmet>
        <title>AdSense & Advertising Policy – Angel Number 333 | Ad Disclosure</title>
        <meta name="description" content="Google AdSense and advertising policy for theangelnumber333.com. Understand how we use ads, cookies, and third-party services while providing angel number content." />
        <link rel="canonical" href="https://www.theangelnumber333.com/adsense-policy" />
        <meta property="og:title" content="AdSense & Advertising Policy – Angel Number 333" />
        <meta property="og:description" content="Google AdSense and advertising policy for theangelnumber333.com. How we use ads and cookies." />
        <meta property="og:url" content="https://www.theangelnumber333.com/adsense-policy" />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="Angel Number 333 Meaning" />
      </Helmet>
      <div className="pt-24 pb-16">
        <div className="container mx-auto px-4">
          <nav className="flex items-center gap-1 text-sm text-muted-foreground mb-6 max-w-3xl mx-auto">
            <Link to="/" className="hover:text-primary">Home</Link>
            <ChevronRight className="h-3 w-3" />
            <span className="text-foreground">AdSense Policy</span>
          </nav>

          <div className="max-w-3xl mx-auto prose prose-sm">
            <h1 className="font-serif text-3xl font-bold text-foreground mb-8">AdSense Policy</h1>
            <div className="text-muted-foreground leading-relaxed space-y-4 [&_h2]:font-serif [&_h2]:text-xl [&_h2]:font-bold [&_h2]:text-foreground [&_h2]:mt-8 [&_h2]:mb-3 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1">
              <p>Last updated: February 23, 2026</p>
              <p>This page explains how theangelnumber333.com uses Google AdSense and third-party advertising services, and how they may affect your browsing experience.</p>

              <h2>About Google AdSense</h2>
              <p>We use Google AdSense to display advertisements on our website. Google AdSense is a program run by Google that allows website publishers to earn revenue by displaying targeted ads alongside their content. These ads are managed and served by Google.</p>

              <h2>How Ads Are Displayed</h2>
              <p>Ads shown on this website are generated by Google's advertising platform. They may be personalized based on your browsing history, interests, and demographic data. Google uses cookies and web beacons to serve ads based on your prior visits to our website and other websites on the internet.</p>

              <h2>Cookies and Personalized Advertising</h2>
              <p>Google's use of advertising cookies enables it and its partners to serve ads to you based on your visit to our site and/or other sites on the internet. You may opt out of personalized advertising by visiting <a href="https://www.google.com/settings/ads" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Google Ads Settings</a>.</p>
              <p>For more information about how Google uses data when you use our site, visit <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Google's Privacy & Terms</a>.</p>

              <h2>Third-Party Vendors and Ad Networks</h2>
              <p>Third-party vendors, including Google, use cookies to serve ads based on a user's prior visits to our website. These vendors may include:</p>
              <ul>
                <li>Google AdSense / Google Ad Manager</li>
                <li>Google Analytics (for audience measurement)</li>
                <li>Other certified ad networks in the Google Display Network</li>
              </ul>
              <p>You can opt out of third-party vendor cookies for personalized advertising by visiting <a href="https://optout.aboutads.info/" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">aboutads.info</a>.</p>

              <h2>Content Guidelines</h2>
              <p>We are committed to ensuring all content on our website complies with Google AdSense Program Policies. Our content is original, valuable, and created for our users' benefit. We do not engage in any practices that violate AdSense policies, including but not limited to:</p>
              <ul>
                <li>Clicking our own ads or encouraging others to do so</li>
                <li>Placing ads on pages with prohibited content</li>
                <li>Manipulating ad placements to deceive users</li>
                <li>Using automated tools to generate clicks or impressions</li>
              </ul>

              <h2>Ad Placement</h2>
              <p>Ads on theangelnumber333.com are placed in clearly designated areas that are distinguishable from our editorial content. We ensure that ads do not interfere with the user experience or mislead visitors into clicking them accidentally.</p>

              <h2>User Experience</h2>
              <p>We strive to maintain a balance between advertising and content to provide an optimal reading experience. If you find any ad inappropriate or disruptive, please <Link to="/contact-us" className="text-primary hover:underline">contact us</Link> and we will address the issue promptly.</p>

              <h2>Changes to This Policy</h2>
              <p>We may update this AdSense Policy from time to time to reflect changes in advertising practices or regulatory requirements. Any updates will be posted on this page with a revised "Last updated" date.</p>

              <h2>Related Policies</h2>
              <p>For more information about how we handle your data and your rights, please refer to:</p>
              <ul>
                <li><Link to="/privacy-policy" className="text-primary hover:underline">Privacy Policy</Link></li>
                <li><Link to="/cookie-policy" className="text-primary hover:underline">Cookie Policy</Link></li>
                <li><Link to="/disclaimer" className="text-primary hover:underline">Disclaimer</Link></li>
                <li><Link to="/affiliate-disclosure" className="text-primary hover:underline">Affiliate Disclosure</Link></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default AdSensePolicy;
